#+HTML: <div id="edn">
#+HTML: {:title "Building a static website with Flask" :date "2017-06-26" :tags ["python", "flask", "org-mode"]}
#+HTML: </div>
#+OPTIONS: \n:1 toc:nil num:0 todo:nil ^:{}
#+PROPERTY: header-args :eval never-export
#+DATE: 2017-06-26 Mon

This describes my pre-clojure static website. My website is now written in Clojure. See [[http://nickgeorge.net/programming/building-my-static-clojure-website/][here]] for my current implementation

* Website- goals
I want place to publicly share my projects, notes, and CV. This way I can display what I am working on, and learn about web development with Flask.
Once I am up and running, I will continue writing my posts in Emacs org-mode and will update the site using org-publish and git-hooks. 

** Why Flask?
I started using [[https://jekyllrb.com/][Jekyll]], the popular static website generator written in Ruby and recommended by Github. However, the focus of Jekyll is blogging, and I don't really want to blog. I see myself posting projects, notes, and the occasional blogpost, but not daily blogs. I felt constrained by Jekyll, as I couldn't figure out how to tweak the layout of the website just so. I also don't code in Ruby and didn't really want to put the time into learning Jekyll as an application. 
However, I do want to build a static site so that I can host on Github pages and easily edit it. But maybe in the future I will want to scale up... For these reasons, (and the fact that I know Python) I looked to [[http://flask.pocoo.org/][Flask]].

However, as far as I can tell, Flask is not widely used for static websites hosted on Github pages. It took me a little while to figure out, but I now have a workable solution for my website which I will talk about on this page. Here are some of the resources I have been using:

** Flask tools
- [[http://flask.pocoo.org/][Flask]] powerful micro-framework written in Python
- [[https://pythonhosted.org/Flask-FlatPages/][Flask-FlatPages]] generate the pages
- [[https://pythonhosted.org/Frozen-Flask/][Frozen-Flask]] for making the static site out of your Flask app
- [[https://www.youtube.com/watch?v=WfpFUmV1d0w][Michael Herman's]] video on using Flask to setup a static website
  - [[https://github.com/mjhea0/flask-intro-1][Github Repo]]. As far as I can tell, this is the Github repo with code. I used it to explain some concepts not covered in the first video
- [[http://stevenloria.com/hosting-static-flask-sites-for-free-on-github-pages/][Steven Loria's]] description of hosting static sites on Github pages using Flask.
  - [[http://killtheyak.com/][Kill The Yak]] is his website hosted on Github
- [[https://nicolas.perriault.net/code/2012/dead-easy-yet-powerful-static-website-generator-with-flask/][Nicolas Perriault]] has an excellent and clear walk through. I learned a ton about Jinja2, the templating engine Flask uses by following along with these code examples.
- [[https://exyr.org/2010/Flask-Static/][Flask static]] basics
- [[http://www.jamesharding.ca/posts/simple-static-markdown-blog-in-flask/][Routes and stuff]] very helpful site for setting up a more complex indexing structure. 
** Website Design Resources
- [[https://v4-alpha.getbootstrap.com/][Bootstrap]]
From the folks at Twitter, this super popular HTML/JS/CSS framework for making beautiful responsive websites. 
- [[https://www.w3schools.com/][W3 Schools]]
For learning HTML, CSS, and how to use Bootstrap

** Emacs and org-mode
- [[https://www.gnu.org/software/emacs/][Emacs]] text editor
- [[http://orgmode.org/][Org-mode]]
  - [[http://orgmode.org/worg/][community driven]] org tutorials
  - [[http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Org-publish]] I use a modified version of this framework to build this website.
  - [[http://orgmode.org/worg/org-tutorials/org-jekyll.html][org-jekyll blog]] is described here. I started using this then modified the workflow for Flask here. 


* Site Overview
Flask is an incredibly light-weight and simple option for creating applications. I am just learning it so I thought building this static website would be a great way to get introduced. There are tons of great tutorials on Youtube and other blogs, some of which I linked to above. I will go through the basics for getting a site on Github pages using Flask, Flask-FlatPages, and Frozen-Flask. My workflow includes using Emacs and org-mode to create my pages in a separate directory, which I then use org-publish to convert these changes to html for the website. First I will describe how too setup your directories and Flask app, then I will show how I have integrated Emacs org-mode to make it all easy and painless. 
** Walk through design
*** I made a cookiecutter!
 [[file:~/personal_projects/cookiecutter-static-flask/][cookiecutter]] in a venv called cookiecutter
BELOW is not yet done. I will 

** Emacs Org mode exports to these locations
publish all https://stackoverflow.com/questions/21258769/using-emacs-org-mode-how-to-publish-the-unchanged-files-in-a-project
** DNS stuff
I use namecheap to manage my custom domain ([[https://nickgeorge.net][nickgeorge.net]]), but unfortunately when I created a CNAME file to connect my github pages to it, I got a horrible network certificate warning from Chrome. To address this, I set this up https://www.timble.net/blog/2016/04/setting-up-ssl-on-github-pages/
namecheap instructions
https://www.namecheap.com/support/knowledgebase/article.aspx/9645/2208/how-do-i-link-my-domain-to-github-pages

/First published: {{{date}}}/
/last updated: {{{time(%Y-%m-%d %a)}}}/
