#+HTML: <div id="edn">
#+HTML: {:title "Static clojure site part XX: What's left to do" :date "2018-08-09" :tags (clojure)}
#+HTML: </div>
#+OPTIONS: \n:1 toc:nil num:0 todo:nil ^:{}
#+PROPERTY: header-args :eval never-export

* What's left to do? 

  Not too much really! I would really like to parse the dates and sort the posts I put in the index page in reverse chronological order. Eventually, I will add a separate /archives/ page to hold all the posts, and a "click here for archives" link at the bottom, but I don't think that will be too difficult once I handle the dates and sorting. My general approach will likely be to parse the dates and use those as keys for the post links or something. Then I can sort the keys and insert the first 10 or so, before adding a "click here for all posts" link to the bottom that goes to a separate "science-archives" or "programming-archives" page with /all/ the links for the relevant posts sorted. I'll have to play with the parsing stuff, but this should be fun. I'd also like to make these functions more resilient. Right now, the =edn= reading functions are /very/ fragile. Misformed =edn= or missing quotes will crash it, giving a Java null pointer exception and no useful debugging info. I want to use ={:pre :post}= conditions, as described [[https://github.com/bbatsov/clojure-style-guide#pre-post-conditions][here]], or =when= statements to handle this and make it a bit more resilient. 

Tests are also on the horizon!

Coming very soon!
