* about
How do you efficiently organize your microscopy data?

* post
Microscopy data is a huge part of my scientific work, and I have developed a few heuristics when dealing with it to keep myself organized and help me find what I need quickly. 

My project involves a number of different types of microscopes (confocal, widefield, multiphoton, stimulated emission depletion (STED), etc.) each with it's own (often proprietary) file format. On top of this, I work with professional research assistants and fellow students who will sometimes take images for me and who I may need to contact with questions in the future. 
How do you stay organized when you have multiple people taking data on different days on different microscopes for the same project?
Early on, I developed the following directory structure for microscopy experiments on my external hard drive (mirrored on the backup server):

#+BEGIN_EXAMPLE
mnc
├── cdb_nikon
├── core_olympus
├── macklin_leica
├── cdb_leica
...
#+END_EXAMPLE

The base directory is the name of the project that this data is being taken for, in this case it is my main project called =mnc=. Under the main =mnc= directory is a separate directory for each microscope. So =cdb_nikon= and =cdb_leica= stand for the department of cell and developmental biology Nikon and Leica microscopes. =core_olympus= means the Light Microscopy Core's Olympus microscope, and =macklin_leica= is the Macklin Lab's Leica microscope. 

Under each microscope is a directory named using the *<ISO8086>!CHECK* 
